### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Ninja-FSE** [traefikturkey/onramp#13]
But how do i enable Authelia or Authentik to my apps?
I have enabled them with "make enable-service authelia" and restarted with "make" i can browse all apps pages but i dont get to the auth.domain.tld.

And in traefik dashboard i can not see any middleware to the routers.

**Comment by mafen** [comment]
I have made some changes to the files in question (.env template, authelia.yml and authentik.yml), 

could you try now? #

**Comment by ilude** [comment]
Those features along with the cloudflare tunnels are out on the bleeding edge of the project. We need to get some documentation written on getting things going with them "properly". If you do get it going and want to take a stab at writing up some how to docs to be included, we would happily accept pull requests or even write ups here in the issues section 😄

**Comment by Ninja-FSE** [comment]
> Those features along with the cloudflare tunnels are out on the bleeding edge of the project. We need to get some documentation written on getting things going with them "properly". If you do get it going and want to take a stab at writing up some how to docs to be included, we would happily accept pull requests or even write ups here in the issues section 😄

English isnt my native language and im using google transle quite often lol :)

I can report issue when i see them though.

**Comment by mafen** [comment]
If you are using authentik, maybe this guide will help you 

https://github.com/traefikturkey/guides/blob/master/authentik-new-service.md

**Comment by ilude** [comment]
Closing this for now. if there are additional issues please feel free to reopen this or create a new ticket.
