### ISSUE TITLE
[Request] Crowedsec

### ISSUE THREAD

**Issue by Ninja-FSE** [traefikturkey/onramp#17]
Dont know where to apply for requests, maybe you guys should have a discord server or something, but for now i opening an issue instead.

Do you have any plans to add Crowdsec to this stack?

**Comment by mafen** [comment]
@ilude has been wanting to add this. But have not gotten around to doing it, so it is on the list, but has not been looked at in that much detail

**Comment by mafen** [comment]
I have added an WIP version of crowdsec 
https://github.com/traefikturkey/onramp/commit/66406c09ee52e62f60492cc664500642dcb3b264

**Comment by mafen** [comment]
It still needs some work as it only supports individual services atm activated by the middleware

**Comment by mafen** [comment]
Also, I have not tested it externally, only locally
