### ISSUE TITLE
Traefik settings

### ISSUE THREAD

**Issue by Ninja-FSE** [traefikturkey/onramp#21]
for more in-depth traefik configuration traefik should have a settings.yml (or something) in etc/traefik.

At the moment im doing changes in the main "docker-compose.yml" file which isn't the best if i in the future is going to upgrade onramp.

**Comment by mafen** [comment]
At the moment, we have it in the main "docker-compose.yml", and this is done for simplicity and ease of use. This may change in the future, but you are free to make a fork and implement a separate file, and maybe even make a pull request.

As a side note, there is an override feature you may want to look in to, and see if that fits your needs.

**Comment by ilude** [comment]
You can create an override yaml file to change any of the configuration, or use external toml/yaml files in the etc/traefik/externals-enabled directory which will be automatically loaded on restart
