### ISSUE TITLE
Cleanup, Test, & Document Cloudflare Tunnels

### ISSUE THREAD

**Issue by proegssilb** [traefikturkey/onramp#23]
Either I'm missing several things (in which case, they should be documented), or the process of creating a cloudflare tunnel to access stuff behind traefik needs a bit of cleanup.

The major issues I ran into:
- The makefile commands do not have the right service name
- The makefile commands need to be told which docker compose file they're running against
- The credentials file downloaded by `make cloudflare-login` cannot be kept between containers, as it does not get saved to a volume.

...all that is from the "create a tunnel via CLI" flow, not the "create a tunnel via GUI" flow. I haven't tried the GUI flow yet, and I'm not sure how much more time I can afford to spend on testing.

**Comment by mafen** [comment]
The GUI work flow works easier than the CLI flow, but i will look more at the CLI flow when i have time

**Comment by proegssilb** [comment]
OK, maybe I can give the GUI flow a try in the next few days.

**Comment by mafen** [comment]
#4c69c1b look at this

**Comment by proegssilb** [comment]
That looks promising. I'll have to test whether the chown logic works on my machine; the uname-to-uid mapping could be machine specific. Hopefully it isn't, but I suspect testing is the only way to find out. I'll try to get to this soon.

**Comment by proegssilb** [comment]
I'm up and running now, so I guess this is resolved. It'd be nice to see more docs around the repo, but that's probably a different issue for a different day.

**Comment by mafen** [comment]
> I'm up and running now, so I guess this is resolved. It'd be nice to see more docs around the repo, but that's probably a different issue for a different day.

We are open for PRs if you have any suggestions to make it better
